### ISSUE TITLE
Unable to upload release

### ISSUE THREAD

**Issue by nerzhul** [nextcloud/appstore#301]
Please provide the following details for error reports. Ignore in case of a feature request.

## Details

* Browser and browser version: Firefox 48/49 Archlinux 64b

## JavaScript Console Output

If unsure see http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers?answertab=votes#tab-top

## Steps to reproduce

1. Setup tar.gz & signature
2. Click on Upload
3. Error 500 is shown without any information on call https://apps.nextcloud.com/api/v1/apps/releases

**Comment by BernhardPosselt** [comment]
@LukasReschke any logs?

**Comment by BernhardPosselt** [comment]
Can you provide the download link and your certificate for testing it locally?

**Comment by BernhardPosselt** [comment]
@nerzhul ^

**Comment by nerzhul** [comment]
Here is the link => https://ftp.unix-experience.fr/owncloud-sms/v1.8.1.tar.gz

and the signature is 

XfO6mrUjPMcOPaR+NyyKcYkUvbkBOzq12MrZJ7hvf6+DKCFVDxAQBYwDxWeixgLu
DL8XMzT1rLpWpOXhjy7S32ajSHVuovqtzaBU+QbFfh00v3m58ujhUBibpioJTOEM
543sA5c4BWX9YrAd4p1Vn05Fo4LlwzKDubqMg10QsR8XlEpGHAvrToltkthNwm8O
+pAJs4YbGCqOwOK7Ej+P1nYbjZJypE+J7tZAc7uCLdeDUiZfSegN2TC6besAfKI1
vHr0u2Jh8sd88IZYuLaePfeaDA1jy0ALKzjZVg0sy4fFKCELlBvamHZ4gvyIIUTA
VUZZef2xW1cbjAQYrql2yig4jW2HwE47YIc3dM3tnfd4YSa/lt9iHqM5zghv6hBu
1Ud85bNeanfCi0VeOml3uEjiVM+ra8OjvvhseGaEDaVYXa1nsZ4csQQ5p2vhKWuo
6lYCa7VxhIKBImLGm2XCujVRDp7Q+o2ZENjsMFji4XQdhkG/OK6d5D2sx2GcMm/4
LwPpML8/bxqYPCp5qDrzxQg7s9KlP9HpO6gHGjsleQq4FSxy+BgAnTs7Zwh5CViY
eoawMYgbYeSMRfts49wxYqs9ebG0mkkLOAL+Sg6K8z6x1cqQ90aqC5rKqOotNZq3
NTNidyDu9thlh2sMFsb9YxFNl1awpFNdc8HiWbVrKGg=

**Comment by LukasReschke** [comment]
```
Internal Server Error: /api/v1/apps/releases
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 748, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 984, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 629, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/opt/appstore/venv/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/appstore/venv/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/appstore/nextcloudappstore/core/api/v1/views.py", line 157, in post
    info, data = provider.get_release_info(url)
  File "/opt/appstore/nextcloudappstore/core/api/v1/release/provider.py", line 28, in get_release_info
    self.config.download_max_redirects, self.config.download_max_size
  File "/opt/appstore/nextcloudappstore/core/api/v1/release/downloader.py", line 55, in get_archive
    req = session.get(url, stream=True, timeout=timeout)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

**Comment by LukasReschke** [comment]
I guess this is because of the certificate on ftp.unix-experience.fr is not valid (https://www.ssllabs.com/ssltest/analyze.html?d=ftp.unix-experience.fr)

Should probably just catch this and display an error message :)

**Comment by BernhardPosselt** [comment]
Yep that should be the solution. Currently only exceptions which are explicitly marked as api exceptions are returned to the user, everything else silently raises a 500

**Comment by nerzhul** [comment]
hmmm stacktrace only due to missing chain for wosign, anoying, it works perfect into my browser :s

**Comment by nerzhul** [comment]
okay, the missing chain is now fixed, will re-test it when apps.nextcloud.com works :)
