### ISSUE TITLE
Can't update appstore

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#305]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/appstore/nextcloudappstore/urls.py", line 34, in <module>
    namespace='api')),
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/appstore/nextcloudappstore/core/api/urls.py", line 5, in <module>
    namespace='v1')),
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/appstore/nextcloudappstore/core/api/v1/urls.py", line 3, in <module>
    from nextcloudappstore.core.api.v1.views import AppView, AppReleaseView, \
  File "/opt/appstore/nextcloudappstore/core/api/v1/views.py", line 6, in <module>
    from pymple import Container
  File "/opt/appstore/venv/lib/python3.5/site-packages/pymple/__init__.py", line 1, in <module>
    from pymple.container import Container
  File "/opt/appstore/venv/lib/python3.5/site-packages/pymple/container.py", line 1, in <module>
    from typing import Callable, Any, TypeVar, Type
ImportError: cannot import name 'Type'
```

cc @BernhardPosselt

**Comment by BernhardPosselt** [comment]
Weird, works just fine locally and on travis https://travis-ci.org/BernhardPosselt/pymple

**Comment by BernhardPosselt** [comment]
Tried it in my local Ubuntu VM and works fine too

**Comment by BernhardPosselt** [comment]
Related to https://github.com/nextcloud/appstore/pull/304 ?

**Comment by BernhardPosselt** [comment]
so what i did was to reproduce this in a very small context:

    pyvenv venv
    source venv/bin/activate
    pip install --upgrade wheel
    pip install --upgrade pip
    pip install pymple
    python3
    from pymple import Container

**Comment by BernhardPosselt** [comment]
Maybe try to activate the venv and run:

    pip install --upgrade typing
    pip install --upgrade pymple

then restart the server

**Comment by BernhardPosselt** [comment]
Fixed
