### ISSUE TITLE
500 fatal server error

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/appstore#384]
When @icewind1991 tried to register his app with http://pastebin.com/h98eVQue this resulted in a 500 server error.

@BernhardPosselt any idea?

```
Internal Server Error: /api/v1/apps
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/opt/appstore/venv/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/appstore/venv/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/appstore/nextcloudappstore/core/api/v1/views.py", line 69, in post
    app_id = validator.get_cn(certificate)
  File "/opt/appstore/nextcloudappstore/core/certificate/validator.py", line 100, in get_cn
    cert = self._to_cert(certificate)
  File "/opt/appstore/nextcloudappstore/core/certificate/validator.py", line 118, in _to_cert
    return load_certificate(FILETYPE_PEM, certificate.encode())
  File "/opt/appstore/venv/lib/python3.5/site-packages/OpenSSL/crypto.py", line 1661, in load_certificate
    _raise_current_error()
  File "/opt/appstore/venv/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'PEM_read_bio', 'bad end line')]
```

**Comment by icewind1991** [comment]
Somehow while copy pasting the formatting of the public key got messed up.

This should show an "Could not parse certificate" or something error to the user

**Comment by LukasReschke** [comment]
Fixed.
