### ISSUE TITLE
Cannot Upload App Release Due to Internal-Server-Error

### ISSUE THREAD

**Issue by schrieveslaach** [nextcloud/appstore#596]
## Details

* Firefox 65

## JavaScript Console Output

```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). new:1:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
```

## Steps to reproduce

1. Visit: https://apps.nextcloud.com/developer/apps/releases/new
2. Enter URL: https://gitlab.com/schrieveslaach/nextcloud-spgverein-app/-/jobs/artifacts/master/raw/spgverein.tar.gz?job=package
3. Enter signature:

```
xWtTkDpR2DAb9/kzwTyoiy7GbgK4+iP24j5j67NusuYQOygQkavHk3PEusqw7Y/0
Dg0WOmi2BZuvM3dYN8YeS+kzXJDmsPuQRQg2IllKmY+jFGfKf7O9omWDlrKe2QP/
2AjGw1ABbCo6L1JAsZy7UOJ3DIpqsl3nvNaQTwHYkGEpD+xVKjlgSiGyn40M20w8
o4+NiXnch/bcK1IvOgwdBzFRlgscExB1/jvk3RTqBvkF8rsqwVd+z7osXd5S1+8R
XkfgTptB+iMkZVFnvzJOkGdBrH9qCFfDbFXx6rgP7/JR3DY/y0nojXHUg9rwyxBX
dgKcHeZxekFWM5o+Z5gPy/MgThQQ0eTUW+MP0wIzCSUgVEWgNgKnqSILVm0NlQ2h
hY7/C062LvoC9F4K3nM11i73GYRd1fUzrQIRMAtBJLP+Kdh/0TpK+MBJoXjjG3Au
b5XpeYAwC6ndE6mL/WhwM2IDyFL9Ynn/lHdvxHMDOa+HN6tm9tHo+N2rPZ8yylk5
uFQ1atmkUeSZxkjfoUBODBOAdPH3e6kUmZ2H13T/vEiasC1NweyWKhoWcpmEuAMA
HiNCCam1wuR/Mmx9g0J2Bel17WERF5lKwx1QHmzLNYP9IqyEeNo9+91C5zzme0xO
Vl4izcZVQ2NV9Ee1otPdrY9Gj889Xt6CeDG3G7uG9Lg=
```

4. Then, hit upload button.

When I look at the network panel, I get two repsonses (200 and 500):

![grafik](https://user-images.githubusercontent.com/16558417/52494491-73f1e200-2bce-11e9-9c4c-78bab7ce86c8.png)

**Comment by BernhardPosselt** [comment]
Needs logs @MorrisJobke

**Comment by MorrisJobke** [comment]
```
Internal Server Error: /api/v1/apps/releases
Traceback (most recent call last):
  File "/usr/lib/python3.5/tarfile.py", line 1629, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1605, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.5/tarfile.py", line 2279, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.5/tarfile.py", line 1082, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.5/gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'sp')
```


Looks like a duplicate of #590
