### ISSUE TITLE
API Returns outdated list of known releases

### ISSUE THREAD

**Issue by duritong** [nextcloud/appstore#623]
https://apps.nextcloud.com/api/v1/platforms.json

Latest release is 16.0.1 though nextcloud has 16.0.4 released.

**Comment by BernhardPosselt** [comment]
There should be a cronjob that does the syncing with GitHub, any idea @nickvergessen ?

**Comment by blizzz** [comment]
perhaps it should, but there is not

**Comment by BernhardPosselt** [comment]
https://nextcloudappstore.readthedocs.io/en/latest/prodinstall.html#sync-nextcloud-releases-from-github

**Comment by blizzz** [comment]
yupp, on it.

**Comment by blizzz** [comment]
Uh, I am having errors only:

```bash
# python manage.py syncnextcloudreleases --oldest-supported="15.0.0" --print
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```
```bash
# venv/bin/python manage.py syncnextcloudreleases --oldest-supported="15.0.0" --print
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 204, in fetch_command
    app_name = commands[subcommand]
KeyError: 'syncnextcloudreleases'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 211, in fetch_command
    settings.INSTALLED_APPS
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 126, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

the SECRET_KEY is set in the production configuration.

You've got an idea?

**Comment by BernhardPosselt** [comment]
Sounds like you are not in the venv

**Comment by BernhardPosselt** [comment]
You need to set an env variable for the settings:

    export DJANGO_SETTINGS_MODULE=nextcloudappstore.settings.production

it's a bit further up in the docs

**Comment by blizzz** [comment]
ah, that's it. Thanks!

**Comment by duritong** [comment]
Thanks, will this now be synced regularely by a cron?

**Comment by blizzz** [comment]
> Thanks, will this now be synced regularely by a cron?

yes

**Comment by nickvergessen** [comment]
Btw, I wondered what you are abusing this API for. Mind to share your usecase?

**Comment by duritong** [comment]
I am fetchting the latest version, as well as the latest versions of certain apps to bundle everything as part of a CI pipeline. Badically I am generating new bundled artifacts for further roll out.
