### ISSUE TITLE
HTTP 500 instead of 404 on unknown category

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/appstore#714]
* open https://apps.nextcloud.com/category/auth
* actual: get a 500 and a log entry
* expected: get a 404

Log line:

```
Internal Server Error: /categories/auth
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/opt/appstore/nextcloudappstore/core/views.py", line 222, in get_context_data
    context['current_category'] = Category.objects.get(id=category_id)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
nextcloudappstore.core.models.Category.DoesNotExist: Category matching query does not exist.
```

cc @mario

**Comment by mario** [comment]
Page not found

The page you are looking for does not exist!


-- This is what I get @MorrisJobke ?

**Comment by mario** [comment]
Ah your link was wrong. Should be /categories/auth
